# Generated by Django 5.2.1 on 2025-06-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_book_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='offer_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='offer_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
