# Generated by Django 5.2.1 on 2025-06-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_book_is_offer_book_offer_expiry_book_offer_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
