# Generated by Django 5.1.3 on 2025-07-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_order_is_paid_order_payment_id_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('razorpay', 'Razorpay'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery')], max_length=20, null=True),
        ),
    ]
