# Generated by Django 5.2.1 on 2025-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('razorpay', 'Razorpay'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery'), ('credit_card', 'Credit Card')], max_length=20, null=True),
        ),
    ]
