# Generated by Django 5.2.1 on 2025-07-07 14:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingaddress',
            unique_together={('user', 'full_name', 'phone', 'address', 'city', 'state', 'zip_code')},
        ),
    ]
