# Generated by Django 5.2.1 on 2025-07-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_alter_shippingaddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
